accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # url(r'login/$', views.LoginView.as_view(), name="login"),
    url(r'logout/$', views.LogoutView.as_view(), name="logout"),
]

filter_site/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'', include('filters.urls', namespace="filter")),
    url(r'^qualify_urls/', include('qualify_urls.urls', namespace="qualify")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filters/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.upload_file, name='main_app'),
    url(r'^keywords/$', views.filter_keywords_list, name='keywords'),
    url(r'^keyword_create/$', views.keyword_create, name='keyword_create'),
    url(r'^(?P<keyword_pk>\d+)/keyword_edit/$', views.keyword_edit, name='keyword_edit'),
    url(r'^(?P<keyword_pk>\d+)/keyword_delete/$', views.keyword_delete, name='keyword_delete'),
    url(r'^url_to_domain/$', views.url_to_domain, name='url_to_domain'),
    url(r'^(?P<vrpage_pk>\d+)/qualify_url/$', views.qualify_url, name='qualify_url'),
    url(r'^(?P<vrpage_pk>\d+)/vrpage_keywords_list/$', views.vrpage_keywords_list, name='vrpage_keywords_list'),
    url(r'^qualify_url_list/$', views.qualify_url_list, name='qualify_url_list'),
    url(r'^keywords_cbv/$', views.KeywordListView.as_view(), name='keywords_cbv'),
    url(r'^keyword_create_cbv/$', views.KeywordCreateView.as_view(), name='keyword_create_cbv'),
    url(r'^(?P<pk>\d+)/keyword_edit_cbv/$', views.KeywordUpdateView.as_view(), name='keyword_edit_cbv'),
    url(r'^(?P<pk>\d+)/keyword_delete_cbv/$', views.KeywordDeleteView.as_view(), name='keyword_delete_cbv'),
    url(r'^linkedin/$', views.linkedin_profile_create, name='linkedin'),
    url(r'^linkedin_list/$', views.linkedin_profile_list, name='linkedin_list'),
]

qualify_urls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.qualify_form, name='qualify_form'),
]

filters/models.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models


# Create your models here.
class Filter(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    order = models.IntegerField(default=0)
    keyword = models.CharField(max_length=255)

    def __str__(self):
        return self.keyword

    def get_absolute_url(self):
        return reverse("filter:keywords_cbv")


class VRPage(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Keyword(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=255)
    vrpage = models.ForeignKey(VRPage)

    def __str__(self):
        return self.name


class LinkedinProfile(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    profile_link = models.URLField(max_length=200)
    # checker = models.ForeignKey(User)

    def __str__(self):
        return self.profile_link


class ExceptTld(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    tld = models.CharField(max_length=15)

    def __str__(self):
        return self.tld

qualify_urls/models.py
from django.db import models

# Create your models here.

filters/forms.py
from django import forms

from . import models

class UploadFileForm(forms.Form):
    file = forms.FileField()
    shepard_urls = forms.BooleanField(initial=True, required=False)


class KeywordForm(forms.ModelForm):
    class Meta:
        model = models.Filter
        fields = [
            'order',
            'keyword'
        ]


class UrlToDomainForm(forms.Form):
    input_urls = forms.CharField(widget=forms.Textarea)


class QualifyURLForm(forms.Form):
    raw_url = forms.URLField()


class LinkedinProfileForm(forms.ModelForm):
    class Meta:
        model = models.LinkedinProfile
        fields = [
            'profile_link',
        ]

    def clean(self):
        cleaned_data = super(LinkedinProfileForm, self).clean()
        profile_link = cleaned_data.get("profile_link")

        profile_list = [str(profile) for profile in models.LinkedinProfile.objects.all()]

        if profile_link in profile_list:
            raise forms.ValidationError("This profile already exist in our database!")


qualify_urls/forms.py
from django import forms

VR_PAGES = (
    ('History of Scrapbooking', 'History of Scrapbooking'),
    ('Kaizen', 'Kaizen'),
    ('Travel Warnings and Alerts', 'Travel Warnings and Alerts'),
    ('Paper Preservation', 'Paper Preservation'),
)

class QualifyURLForm(forms.Form):
    file = forms.FileField()
    vrpage = forms.ChoiceField(choices=VR_PAGES)

filters/views.py
import html5lib
import requests
import tldextract
from bs4 import BeautifulSoup
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.generic import (
    ListView,
    CreateView, UpdateView, DeleteView
)
from requests import exceptions

from . import forms
from .models import Filter, Keyword, VRPage, LinkedinProfile, ExceptTld
from . import functions
from . import mixins


@login_required
def filter_keywords_list(request):
    keywords = Filter.objects.all()
    return render(request, 'filters/keywords_list.html', {'keywords': keywords})


@login_required
def upload_file(request):
    if request.method == 'POST':
        form = forms.UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            functions.handle_uploaded_file(request.FILES['file'])
            raw_urls = []
            bad_urls = []
            good_urls = []
            bad_tlds = []
            keywords = [str(keyword) for keyword in Filter.objects.all()]
            tlds = [str(tld) for tld in ExceptTld.objects.all()]
            functions.csv_reader('media/raw_urls.csv', raw_urls)
            if form.cleaned_data['shepard_urls'] == True:
                functions.filter_shepard(raw_urls, keywords, bad_urls,
                                         good_urls, tlds, bad_tlds)
            else:
                functions.filter_arrow(raw_urls, keywords, bad_urls, good_urls)
            functions.save_csv('media/cleanurls.csv', good_urls)
            functions.save_csv('media/badurls.csv', bad_urls)
            functions.save_csv('media/badtlds.csv', bad_tlds)
            return render(request, 'filters/upload.html', {'form': form,
                                                           'raw_urls': raw_urls,
                                                           'good_urls': good_urls,
                                                           'bad_urls': bad_urls,
                                                           'bad_tlds': bad_tlds})
    else:
        form = forms.UploadFileForm()
    return render(request, 'filters/upload.html', {'form': form})


@login_required
def keyword_create(request):
    form = forms.KeywordForm()
    if request.method == 'POST':
        form = forms.KeywordForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('filter:keywords'))
    return render(request, 'filters/keyword_form.html', {'form': form})


@login_required
def keyword_edit(request, keyword_pk):
    keyword = get_object_or_404(Filter, pk=keyword_pk)
    form = forms.KeywordForm(instance=keyword)
    if request.method == 'POST':
        form = forms.KeywordForm(instance=keyword, data=request.POST)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect(reverse('filter:keywords'))
    return render(request, 'filters/keyword_form.html', {'form': form})


@login_required
def keyword_delete(request, keyword_pk):
    keyword = get_object_or_404(Filter, pk=keyword_pk).delete()
    return HttpResponseRedirect(reverse('filter:keywords'))


@login_required
def url_to_domain(request):
    form = forms.UrlToDomainForm()
    if request.method == 'POST':
        form = forms.UrlToDomainForm(request.POST)
        if form.is_valid():
            urls = form.cleaned_data['input_urls'].splitlines()
            domain_list = []
            for url in urls:
                domain = tldextract.extract(url).registered_domain
                domain_list.append(domain)
            return render(request, 'filters/url_to_domain.html', {'form': form, 'domain_list': domain_list})
    return render(request, 'filters/url_to_domain.html', {'form': form,})


@login_required
def qualify_url_list(request):
    vrpages = VRPage.objects.all()
    return render(request, 'filters/qualify_url_list.html', {'vrpages': vrpages})


@login_required
def qualify_url(request, vrpage_pk):
    form = forms.QualifyURLForm()
    vrpage = get_object_or_404(VRPage, pk=vrpage_pk)
    if request.method == 'POST':
        form = forms.QualifyURLForm(request.POST)
        if form.is_valid():
            keywords = [str(keyword) for keyword in Keyword.objects.filter(vrpage=vrpage_pk)]
            keywords_present = []
            raw_url = form.cleaned_data['raw_url']
            try:
                resp = requests.get(raw_url)
            except exceptions.ContentDecodingError:
                messages.add_message(request, messages.ERROR,
                    'ContentDecodingError occurred!')
            else:
                content = resp.text.lower()
                soup = BeautifulSoup(content, 'html5lib')
                content = soup.get_text()
                if resp.ok:
                    for keyword in keywords:
                        if keyword in content:
                            counter = content.count(keyword)
                            keywords_present.append([keyword, counter])
                    if keywords_present:
                        messages.add_message(request, messages.SUCCESS,
                            "found.")
                    else:
                        messages.add_message(request, messages.INFO,
                            'No keywords found.')
                else:
                    messages.add_message(request, messages.ERROR,
                        'An error occurred. Error code: {}'.format(resp.status_code))

                return render(request, 'filters/qualify_url.html',
                              {'form': form, 'keywords_present': keywords_present, 'vrpage': vrpage})
    return render(request, 'filters/qualify_url.html', {'form': form, 'vrpage': vrpage})


def vrpage_keywords_list(request, vrpage_pk):
    keywords = Keyword.objects.filter(vrpage=vrpage_pk)
    return render(request, 'filters/vrpage_keywords_list.html', {'keywords': keywords})


class KeywordListView(LoginRequiredMixin, ListView):
    context_object_name = "keywords"
    model = Filter


class KeywordCreateView(LoginRequiredMixin, mixins.PageTitleMixin, CreateView):
    fields = ("order", "keyword")
    model = Filter
    page_title = "Create Keyword"


class KeywordUpdateView(LoginRequiredMixin, mixins.PageTitleMixin, UpdateView):
    fields = ("order", "keyword")
    model = Filter

    def get_page_title(self):
        obj = self.get_object()
        return "Edit {}".format(obj.keyword)


class KeywordDeleteView(LoginRequiredMixin, DeleteView):
    model = Filter
    success_url = reverse_lazy("filter:keywords_cbv")


@login_required
def linkedin_profile_list(request):
    linkedin_profiles = LinkedinProfile.objects.all()
    return render(request, 'filters/linkedin_profile_list.html', {'linkedin_profiles': linkedin_profiles})

@login_required
def linkedin_profile_create(request):
    form = forms.LinkedinProfileForm()
    linkedin_profiles = len(LinkedinProfile.objects.all())
    if request.method == 'POST':
        form = forms.LinkedinProfileForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS,
                'LinkedIn profile has been successfully added!')
            return HttpResponseRedirect(reverse('filter:linkedin'))
    return render(request, 'filters/linkedin.html', {'form': form, 'profiles': linkedin_profiles})

qualify_urls/views.py
import html5lib
import requests
from bs4 import BeautifulSoup
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404
from requests import exceptions

from . import forms
from . import functions
from filters.models import VRPage


@login_required
def qualify_form(request):
    form = forms.QualifyURLForm()
    if request.method == 'POST':
        form = forms.QualifyURLForm(request.POST, request.FILES)
        if form.is_valid():
            functions.handle_uploaded_file(request.FILES['file'])
            raw_urls = []
            has_keywords = []
            no_keywords = []
            urls_with_errors = []
            selected_vrpage = form.cleaned_data['vrpage']
            vrpage = get_object_or_404(VRPage, name=selected_vrpage)
            keywords = [str(keyword) for keyword in vrpage.keyword_set.all()]
            functions.csv_reader('media/qualify_urls.csv', raw_urls)
            for raw_url in raw_urls:
                try:
                    resp = requests.get(raw_url[0])
                except exceptions.RequestException:
                    urls_with_errors.append(raw_url)
                else:
                    if resp.ok:
                        content = resp.text.lower()
                        soup = BeautifulSoup(content, 'html5lib')
                        content = soup.get_text()
                        keywords_list = []
                        for keyword in keywords:
                            if keyword in content:
                                counter = content.count(keyword)
                                keywords_list.append([keyword, counter])
                        if keywords_list:
                            raw_url.insert(1, len(keywords_list))
                            raw_url.insert(2, keywords_list)
                            has_keywords.append(raw_url)
                        else:
                            no_keywords.append(raw_url)
                    else:
                        urls_with_errors.append(raw_url)
            functions.save_csv('media/has_keywords.csv', has_keywords)
            functions.save_csv('media/no_keywords.csv', no_keywords)
            functions.save_csv('media/urls_with_errors.csv', urls_with_errors)
            return render(request, 'qualify_urls/qualify_form.html', {'form': form,
                                                           'raw_urls': raw_urls,
                                                           'has_keywords': has_keywords,
                                                           'no_keywords': no_keywords,
                                                           'urls_with_errors': urls_with_errors,})
    return render(request, 'qualify_urls/qualify_form.html', {'form': form})

filters/templates/filters/filter_confirm_delete.html
{% extends "filters/layout.html" %}

{% block title %}Delete Keyword{% endblock %}

{% block content %}
    <div class="container text-xs-center">
      <div class="jumbotron jumbotron-fluid bg-success">
        <div class="container text-sm-center">
          <h1 class="display-2">Filter App</h1>
          <p class="lead">Clean your raw urls by filtering and deleting bad urls!</p>
        </div>
      </div>
      <div>
        <h4 class="m-b-2">Are you sure you want to delete {{ filter.keyword }}?</h4>
        <form action="" method="POST">
            {% csrf_token %}
            <input type="submit" value="Delete" class="btn btn-danger">
            <a href="{% url 'filter:keywords_cbv' %}" class="btn btn-info">Cancel</a>
        </form>
      </div>
    </div>
{% endblock %}

filters/templates/filters/filter_form.html
{% extends "filters/layout.html" %}

{% block title %}{{ page_title }}{% endblock %}

{% block content %}
    <div class="container text-xs-center">
      <div class="jumbotron jumbotron-fluid bg-success">
        <div class="container text-sm-center">
          <h1 class="display-2">Filter App</h1>
          <p class="lead">Clean your raw urls by filtering and deleting bad urls!</p>
        </div>
      </div>
      <div>
        <h4 class="m-b-2">{% if not form.instance.pk %}Create Keyword{% else %}Edit {{ form.instance.keyword }}{% endif %}</h4>
        <form action="" method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Save" class="btn btn-success btn-lg">
        </form>
      </div>
    </div>
{% endblock %}

filters/templates/filters/filter_list.html
{% extends "filters/layout.html" %}

{% block title %}Keywords{% endblock %}

{% block content %}
    <div class="container text-xs-center">
        <div class="jumbotron jumbotron-fluid bg-success">
            <div class="container text-sm-center">
                <h1 class="display-2">Filter App</h1>
                <p class="lead">Clean your raw urls by filtering and deleting bad urls!</p>
            </div>
        </div>
        <div>
        <h4 class="m-b-2">Keyword List</h4>
        <h4>Total: {{ keywords|length }}</h4>
        <a href="{% url 'filter:keyword_create_cbv' %}" class="btn btn-success m-y-2">Create Keyword</a>
        <ul class="list-group">
        {% for keyword in keywords %}
            <li class="list-group-item">
            <a href="{% url 'filter:keyword_delete_cbv' pk=keyword.pk %}"><span class="tag tag-danger tag-pill pull-xs-right">Delete</span></a>
            <a href="{% url 'filter:keyword_edit_cbv' pk=keyword.pk %}"><span class="tag tag-info tag-pill pull-xs-right">Edit</span></a>
            {{ keyword }}
            </li>
        {% endfor %}
        </ul>
    </div>
{% endblock %}

filters/templates/filters/keyword_form.html
{% extends "filters/layout.html" %}

{% block title %}Add Keyword{% endblock %}

{% block content %}
    <div class="container text-xs-center">
      <div class="jumbotron jumbotron-fluid bg-success">
        <div class="container text-sm-center">
          <h1 class="display-2">Filter App</h1>
          <p class="lead">Clean your raw urls by filtering and deleting bad urls!</p>
        </div>
      </div>
      <div>
        <h4 class="m-b-2">Add Keyword</h4>
        <form action="" method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Save" class="btn btn-success btn-lg">
        </form>
      </div>
    </div>
{% endblock %}

filters/templates/filters/keywords_list.html
{% extends "filters/layout.html" %}

{% block title %}Keywords{% endblock %}

{% block content %}
    <div class="container text-xs-center">
        <div class="jumbotron jumbotron-fluid bg-success">
            <div class="container text-sm-center">
                <h1 class="display-2">Filter App</h1>
                <p class="lead">Clean your raw urls by filtering and deleting bad urls!</p>
            </div>
        </div>
        <div>
        <h4 class="m-b-2">Keyword List</h4>
        <h4>Total: {{ keywords|length }}</h4>
        <a href="{% url 'filter:keyword_create' %}" class="btn btn-success m-y-2">Add Keyword</a>
        <ul class="list-group">
        {% for keyword in keywords %}
            <li class="list-group-item">
            <a href="{% url 'filter:keyword_delete' keyword_pk=keyword.pk %}"><span class="tag tag-danger tag-pill pull-xs-right">Delete</span></a>
            <a href="{% url 'filter:keyword_edit' keyword_pk=keyword.pk %}"><span class="tag tag-info tag-pill pull-xs-right">Edit</span></a>
            {{ keyword }}
            </li>
        {% endfor %}
        </ul>
    </div>
{% endblock %}

filters/templates/filters/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}{% endblock %}</title>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/css/bootstrap.min.css" integrity="sha384-MIwDKRSSImVFAZCVLtU0LMDdON6KVCrZHyVQQj6e8wIEJkW4tvwqXrbMIya1vriY" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-dark bg-inverse m-b-2">
      <a class="navbar-brand" href="{% url 'filter:main_app' %}">Polishing Tools</a>
      <ul class="nav navbar-nav">
        <li class="nav-item m-x-2">
          <a class="nav-link" href="{% url 'filter:main_app' %}">Filter <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item m-x-2">
          <a class="nav-link" href="{% url 'filter:keywords_cbv' %}">Keywords</a>
        </li>
        <li class="nav-item m-x-2">
          <a class="nav-link" href="{% url 'filter:url_to_domain' %}">URL2Domain</a>
        </li>
        <li class="nav-item m-x-2">
          <a class="nav-link" href="{% url 'filter:qualify_url_list' %}">Qualify URL</a>
        </li>
        <li class="nav-item m-x-2">
          <a class="nav-link" href="{% url 'filter:linkedin' %}">LinkedIn Checker</a>
        </li>
        <li class="nav-item m-x-2">
          <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
        </li>
      </ul>
    </nav>
    {% block content %}
    {% endblock %}
    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/js/bootstrap.min.js" integrity="sha384-ux8v3A6CPtOTqOzMKiuo3d/DomGaaClxFYdCu2HPMBEkf6x2xiDyJ7gkXU0MWwaD" crossorigin="anonymous"></script>
  </body>
</html>

filters/templates/filters/linkedin.html
{% extends "filters/layout.html" %}
{% load widget_tweaks %}

{% block title %}LinkedIn Profile Checker{% endblock %}

{% block content %}
    <div class="container text-xs-center">
        <div class="jumbotron jumbotron-fluid bg-success">
            <div class="container text-sm-center">
                <h3 class="display-3">LinkedIn Profile Checker</h3>
                <h5>Current total of linkedin profiles: {{ profiles }}</h5>
            </div>
        </div>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-success" role="alert">
                  <strong>Well done!</strong> {{ message }}
                </div>
            {% endfor %}
        {% endif %}

        {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {{ form.non_field_errors }}
            </div>
        {% endif %}
        <form action="" method="POST" class="m-b-3">
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            <h4 class="m-b-2">LinkedIn Profile URL</h4>
            {% for field in form.visible_fields %}
                <div class="form-group">
                    {{ field|add_class:'form-control' }}
                    {#<textarea class="form-control" id="inputurl" rows="15"></textarea>#}
                </div>
            {% endfor %}
            {% csrf_token %}
            <input type="submit" value="Check" class="btn btn-success btn-lg">
        </form>
        <hr class="m-t-3">
        <a class="btn btn-primary" href="{% url 'filter:linkedin_list' %}" role="button">View Profile List</a>
        <h6 class="m-t-3">Version 1.0 by Renelle Tigue</h6>
    </div>
{% endblock %}

filters/templates/filters/linkedin_profile_list.html
{% extends "filters/layout.html" %}

{% block title %}LinkedIn Profiles{% endblock %}

{% block content %}
    <div class="container text-xs-center">
        <div>
        <h4 class="m-b-2">LinkedIn Profile List</h4>
        <h4>Total: {{ linkedin_profiles|length }}</h4>
    </div>
        <table class="table table-hover m-t-3">
            <thead class="thead-default">
                <tr>
                    <th>#</th>
                    <th class="text-xs-center">LinkedIn Profiles</th>
                </tr>
            </thead>
            <tbody>
                {% for profile in linkedin_profiles %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td class="text-xs-center">{{ profile.profile_link }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
{% endblock %}

filters/templates/filters/qualify_url.html
{% extends "filters/layout.html" %}
{% load widget_tweaks %}

{% block title %}Qualify URL{% endblock %}

{% block content %}
    <div class="container text-xs-center">
        <div class="jumbotron jumbotron-fluid bg-success">
            <div class="container text-sm-center">
                <h3 class="display-3">Qualify URL App</h3>
                <p class="lead">Check URL's content for certain keywords</p>
                <p class="lead">VR Page: {{ vrpage.name }}</p>
            </div>
        </div>
        {% if messages %}
            {% for message in messages %}
                {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                    <div class="alert alert-success" role="alert">
                        <strong>Well done!</strong> {{ keywords_present|length }} keyword{{ keywords_present|length|pluralize }} {{ message }}
                    </div>
                {% elif message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
                    <div class="alert alert-info" role="alert">
                        <strong>I'm sorry!</strong> {{ message }}
                    </div>
                {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    <div class="alert alert-danger" role="alert">
                        <strong>Oh snap!</strong> {{ message }}
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
        <form action="" method="POST">
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            <h4 class="m-b-2">Raw URL</h4>
            {% for field in form.visible_fields %}
                <div class="form-group">
                    {{ field|add_class:'form-control' }}
                    {#<textarea class="form-control" id="inputurl" rows="15"></textarea>#}
                </div>
            {% endfor %}
            {% csrf_token %}
            <input type="submit" value="Check" class="btn btn-success btn-lg">
        </form>
        {% if keywords_present %}
            <h4 class="m-t-2">Keywords: {{ keywords_present|length }}</h4>
            <ul class="list-group">
                {% for keyword in keywords_present %}
                <li class="list-group-item">{{ keyword.0 }}
                    <span class="tag tag-info tag-pill pull-xs-right">{{ keyword.1 }}</span>
                </li>
                {% endfor %}
            </ul>
        {% endif %}
        <a href="{% url 'filter:vrpage_keywords_list' vrpage_pk=vrpage.pk %}"><p class="m-t-1">List of Keywords for This VR Page</p></a>
        <h6 class="m-t-3">Version 1.0 by Renelle Tigue</h6>
    </div>
{% endblock %}

filters/templates/filters/qualify_url_list.html
{% extends "filters/layout.html" %}

{% block title %}Qualify URL List{% endblock %}

{% block content %}
    <div class="container text-xs-center">
        <div class="jumbotron jumbotron-fluid bg-success">
            <div class="container text-sm-center">
                <p class="display-2">Qualify URL List</p>
                <p class="lead">Check URL's content for certain keywords</p>
            </div>
        </div>
        <div class="list-group">
            {% for vrpage in vrpages %}
            <a href="{% url 'filter:qualify_url' vrpage_pk=vrpage.pk %}" class="list-group-item list-group-item-action">
                {{ vrpage }}
            </a>
            {% endfor %}
        <hr class="m-t-3">
        <h6>Version 1.0 by Renelle Tigue</h6>
    </div>
{% endblock %}